# Generated by Django 2.2 on 2019-04-26 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gov_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(max_length=100)),
                ('productNo', models.CharField(max_length=50)),
                ('color_code', models.CharField(max_length=20)),
                ('paperNo', models.CharField(max_length=50)),
                ('COANo', models.CharField(max_length=50)),
            ],
        ),
    ]
