# Generated by Django 2.2 on 2019-04-27 02:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gov', '0002_gov_history_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='gov_history',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='govs', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
